apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencut.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "opencut.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.web.env.NODE_ENV | quote }}
  DATABASE_URL: {{ include "opencut.databaseUrl" . | quote }}
  UPSTASH_REDIS_REST_URL: "http://{{ include "opencut.fullname" . }}-serverless-redis-http:80"
  NEXT_PUBLIC_SITE_URL: {{ .Values.web.env.NEXT_PUBLIC_SITE_URL | quote }}
  NEXT_PUBLIC_MARBLE_API_URL: {{ .Values.web.env.NEXT_PUBLIC_MARBLE_API_URL | quote }}
  SRH_MODE: "env"
  SRH_CONNECTION_STRING: "redis://{{ include "opencut.fullname" . }}-redis:6379"
