apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencut.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "opencut.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgres.enabled }}
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
  {{- end }}
  BETTER_AUTH_SECRET: {{ .Values.web.secrets.BETTER_AUTH_SECRET | quote }}
  UPSTASH_REDIS_REST_TOKEN: {{ .Values.serverlessRedisHttp.auth.token | quote }}
  SRH_TOKEN: {{ .Values.serverlessRedisHttp.auth.token | quote }}
  MARBLE_WORKSPACE_KEY: {{ .Values.web.secrets.MARBLE_WORKSPACE_KEY | quote }}
  FREESOUND_CLIENT_ID: {{ .Values.web.secrets.FREESOUND_CLIENT_ID | quote }}
  FREESOUND_API_KEY: {{ .Values.web.secrets.FREESOUND_API_KEY | quote }}
  CLOUDFLARE_ACCOUNT_ID: {{ .Values.web.secrets.CLOUDFLARE_ACCOUNT_ID | quote }}
  R2_ACCESS_KEY_ID: {{ .Values.web.secrets.R2_ACCESS_KEY_ID | quote }}
  R2_SECRET_ACCESS_KEY: {{ .Values.web.secrets.R2_SECRET_ACCESS_KEY | quote }}
  R2_BUCKET_NAME: {{ .Values.web.secrets.R2_BUCKET_NAME | quote }}
  MODAL_TRANSCRIPTION_URL: {{ .Values.web.secrets.MODAL_TRANSCRIPTION_URL | quote }}
