apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencut.fullname" . }}-web
  namespace: {{ .Values.namespace }}
  labels:
    app: web
    {{- include "opencut.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
  selector:
    app: web
